echo "--------------------------------------------------"
echo "Command Selector for MacOS"
echo "--------------------------------------------------"
echo "Action          : Usage"
echo "--------------------------------------------------"
echo "login           : It can log in Google or others account on Google Account."
echo "android         : It can communicate with android, but be required to install SSHelper on your phone."
echo "browser         : It can browse both of your local file and internet URL."
echo "search          : It can search the words on internet by entering that."
echo "screen          : It can change window size to fullscreen and return original size when it runs once again."
echo "closer          : It can close each of internet tabs after each execution, but be required to install chrome-cli on your terminal."
echo "programming     : It can run javascript, python, ruby, php, haskell, and lua code. (They must be installed on your pc and if you want to add the languages you want to program in, you will need to set them up in your custom in the shell script file.)"
echo "calculator      : It can calculate basic arithmetic operations."
echo "logout          : It can log out Google account on Google Account."
echo "poweroff        : It can power off according to sleep, shutdown, and reboot options."
echo "exit            : It can exit from Command Selector."
echo "help            : It will show this message with usage or description."
echo "--------------------------------------------------"
echo "Developing date : 2022,Nov,28th"
echo "Release date    : 2023,Jan,1st"
echo "Version         : 1."
echo "Developer       : Hirotoshi Uchida"
echo "--------------------------------------------------"
bash option.sh
